create schema vitavalore;
use vitavalore;
select * from produtos;
select * from users;
select * from vendas;
select * from empresas;
select * from users;
select * from planos;
SELECT * FROM planos WHERE name = 'Plano Avançado'; 
show tables;